name: React Test & Lint

on:
  push:
    branches:
      - "**"

jobs:
  ci-skip-check:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  jest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    needs: ci-skip-check
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.13.1"
      - name: Cache npm
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm install
      - run: npm test

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    needs: ci-skip-check
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.13.1"
      - name: Cache npm
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm install
      - run: npm run lint
